### ISSUE TITLE
Task 2 - Create wireframes for the project

### ISSUE THREAD

**Issue by dbc2201** [sitanshu-cse10/Facial_Recognition_amcat_secruity#3]
- [x] Integrate your mock-ups to create a wireframe.
This wireframe will be the single source of information of all the interaction among different screens in your software
### Extra
[Intro to Wireframing, by the nice people at Balsamiq](https://balsamiq.com/learn/courses/wireframing/)

**Comment by shobhit00dixit** [comment]
Created and verified.
