### ISSUE TITLE
Task 3 - Publish the wireframes to the project repo

### ISSUE THREAD

**Issue by dbc2201** [sitanshu-cse10/Facial_Recognition_amcat_secruity#4]
- [x] Export your wireframes as a PDF document.

- [x] Import the PDF document inside your project structure inside PyCharm, preferably, "./docs/wireframes/".

- [x] Link the uploaded file inside the readme

**Comment by shobhit00dixit** [comment]
Wireframe published in the specified location "./docs/wireframes/"
[wireframe](https://github.com/sitanshu-cse10/Facial_Recognition_amcat_secruity/blob/master/docs/Wireframe/wireframe.pdf)
